### ISSUE TITLE
Per-release Checklist for iOS  1.10 on iPad mini with iOS12 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1220]
## Per release speciality tests
 - [x] Favourites show low resolution icons for some sites. ([#463](https://github.com/brave/brave-ios/issues/463))
 - [x] Sync UI Updates. ([#719](https://github.com/brave/brave-ios/issues/719))
 - [x] Password lockout timer doesn't disappear after a certain amount of time. ([#938](https://github.com/brave/brave-ios/issues/938))
 - [x] Pinch to Zoom not working correctly on all sites. ([#1023](https://github.com/brave/brave-ios/issues/1023))
 - [x] Borsen.dk website is NOT loading . ([#1061](https://github.com/brave/brave-ios/issues/1061))
 - [x] BVC taskQueue is refilled in setupTabs() leading to crash.. ([#1085](https://github.com/brave/brave-ios/issues/1085))
 - [x] Add ability to go back from nested folder in bookmarks menu.. ([#1165](https://github.com/brave/brave-ios/issues/1165))
 - [x] Bookmarks bottom toolbar UI issues.. ([#1170](https://github.com/brave/brave-ios/issues/1170))
 - [x] New Menu Order Change. ([#1184](https://github.com/brave/brave-ios/issues/1184))
 - [x] Crash when Turning Shields Off. ([#1187](https://github.com/brave/brave-ios/issues/1187))
 - [x] Unable to open bookmark or history. ([#1191](https://github.com/brave/brave-ios/issues/1191))
 - [x] Center Brave Shields Caret. ([#1195](https://github.com/brave/brave-ios/issues/1195))
 - [x] Open in a private tab from bookmarks/history launches it in a new tab. ([#1216](https://github.com/brave/brave-ios/issues/1216))
