### ISSUE TITLE
Per-release Checklist for iOS  1.10 on iPad Pro/5G with iOS12 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1223]
## Per release speciality tests
 - [x] Favourites show low resolution icons for some sites. ([#463](https://github.com/brave/brave-ios/issues/463))
 - [ ] Sync UI Updates. ([#719](https://github.com/brave/brave-ios/issues/719))
 - [x] Password lockout timer doesn't disappear after a certain amount of time. ([#938](https://github.com/brave/brave-ios/issues/938))
 - [x] Pinch to Zoom not working correctly on all sites. ([#1023](https://github.com/brave/brave-ios/issues/1023))
 - [ ] Borsen.dk website is NOT loading . ([#1061](https://github.com/brave/brave-ios/issues/1061))
 - [ ] BVC taskQueue is refilled in setupTabs() leading to crash.. ([#1085](https://github.com/brave/brave-ios/issues/1085))
 - [ ] Unsupported browser message when security key is connected. ([#1148](https://github.com/brave/brave-ios/issues/1148))
 - [ ] Authentication doesn't work when security key is connected and disconnected quickly. ([#1150](https://github.com/brave/brave-ios/issues/1150))
 - [ ] Add support for U2F/WebAuthn hardware security keys on iOS. ([#1159](https://github.com/brave/brave-ios/issues/1159))
 - [ ] Add ability to go back from nested folder in bookmarks menu.. ([#1165](https://github.com/brave/brave-ios/issues/1165))
 - [ ] Bookmarks bottom toolbar UI issues.. ([#1170](https://github.com/brave/brave-ios/issues/1170))
 - [ ] New Menu Order Change. ([#1184](https://github.com/brave/brave-ios/issues/1184))
 - [ ] Crash when Turning Shields Off. ([#1187](https://github.com/brave/brave-ios/issues/1187))
 - [ ] Unable to open bookmark or history. ([#1191](https://github.com/brave/brave-ios/issues/1191))
 - [ ] Center Brave Shields Caret. ([#1195](https://github.com/brave/brave-ios/issues/1195))
 - [ ] Open in a private tab from bookmarks/history launches it in a new tab. ([#1216](https://github.com/brave/brave-ios/issues/1216))
