### ISSUE TITLE
Setup TestFlight Beta Channel

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1846]
### Description: 
Currently Brave iOS has a beta channel that does not support external testing. In order to setup an actual beta channel, the existing beta needs to be re-defined to `dev` and the new beta setup correctly.

This requires
- [x] new provisioning profiles
- [x] new Testflight group
- [x] Update `xcconfig` files to contain correct information
    This will lead to the current `beta` information being moved to `dev` `xcconfig`, and the current `beta` `xcconfig` file being updated with new information.
- [x] Update `isRelease` `AppBuildChannel` to be called something more like `isPublicFacing` and add `.beta` to this value
- [x] Verify app behavior aligns with "release" behavior (e.g. debug settings panel)
- [x] Uploading?
- [x] Setup new `internal` fastlane script to replace the new beta (current `beta`)
