### ISSUE TITLE
Manual test run for 1.13 on iPad running iOS12

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1857]
## Per release speciality tests
 - [x] Use preferences over SQS for sync. ([#1470](https://github.com/brave/brave-ios/issues/1470))
 - [ ] Internal Issue. ([#1478](https://github.com/brave/brave-ios/issues/1478))
 - [x] Search term text colour is too light on dark mode. ([#1525](https://github.com/brave/brave-ios/issues/1525))
 - [ ] Sync devices showing wrong names when tapped. ([#1587](https://github.com/brave/brave-ios/issues/1587))
 - [x] Add Licenses setting option.. ([#1590](https://github.com/brave/brave-ios/issues/1590))
 - [x] Ads should not be enabled by default if the users region is not supported. ([#1647](https://github.com/brave/brave-ios/issues/1647))
 - [ ] Setup Japanese translations for Rewards UI. ([#1698](https://github.com/brave/brave-ios/issues/1698))
 - [ ] Disable contribution to non-verified pubs/videos isn't working. ([#1709](https://github.com/brave/brave-ios/issues/1709))
 - [ ] Missing text changes for JP region. ([#1765](https://github.com/brave/brave-ios/issues/1765))
 - [x] AC contribution message has crazy value for contributed amount. ([#1769](https://github.com/brave/brave-ios/issues/1769))
 - [x] Recurring tips shows exponential value once contribution is through. ([#1770](https://github.com/brave/brave-ios/issues/1770))
 - [x] Internal Issue. ([#1772](https://github.com/brave/brave-ios/issues/1772))
 - [ ] Don't allow ads to appear when the user is typing in the URL bar. ([#1774](https://github.com/brave/brave-ios/issues/1774))
 - [ ] Add BAT Contribution Queue. ([#1781](https://github.com/brave/brave-ios/issues/1781))
 - [x] Tapping on Rewards button notification enters overlay. ([#1787](https://github.com/brave/brave-ios/issues/1787))
 - [x] Update onboarding screen for non-ads regions. ([#1812](https://github.com/brave/brave-ios/issues/1812))
 - [x] Incorrect button during onboarding when regions is changed [Follow up to #1647]. ([#1814](https://github.com/brave/brave-ios/issues/1814))
 - [ ] Publisher Shows as unverified if publisher is visited before publisher list finished parsing. ([#1831](https://github.com/brave/brave-ios/issues/1831))
 - [x] Replace tokens on onboarding for Japanese locale. ([#1842](https://github.com/brave/brave-ios/issues/1842))
 - [x] Auto Contribution details says Next monthly tip date. ([#1844](https://github.com/brave/brave-ios/issues/1844))

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Make sure that data from the last version appears in the new version OK
- [x] Test that the previous version's cookies are preserved in the next version
- [x] Test that saved passwords are retained upon upgrade
- [x] Verify stats are retained when upgrading from the previous version
- [x] Verify per-site settings are retained when upgrading from the previous version
- [x] Verify sync chain created in the previous version is still retained on upgrade

## Bookmarks

- [x] Test that creating a bookmark works
- [x] Test that clicking a bookmark from bookmark manager loads the bookmark
- [x] Test that deleting a bookmark works
- [x] Test that creating a bookmark folder works
- [x] Test that creating a bookmark inside the created folder works
- [x] Test that you can add a bookmark directly inside a bookmark folder
- [x] Test that you can delete a bookmark in edit mode
- [x] Test that you can delete a bookmark folder with bookmarks inside
- [x] Test adding a bookmark domain, subpaths is retained and you are successfully able to visit the domain subpath in a new tab

## Favourites

- [x] Test editing favourite and changing URL updates the favicons accordingly
- [x] Test that you can remove favourites
- [x] Test that you can add new favourites from the share menu

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)
- [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

- [x] Verify search box is shown when selected via the share menu
- [x] Test successful find
- [x] Test forward and backward find navigation
- [x] Test failed to find shows 0 results

## Private Mode

- [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

## Reader Mode
- [x] Visit http://theverge.com, open any article, verify the reader mode icon is shown in the URL bar
- [x] Verify tapping on the reader mode icon opens the article in reader mode
- [x] Edit reader mode settings and open different pages in reader mode and verify if the setting is retained across each article

## History

- [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also, note if the progress bar activates and shows progress
- [x] Settings > Clear Private Data, and clear all. Check only the history is cleared and favourites are retained

## Shields Settings

- [x] Enable all switches in settings and visit a site and disable block scripts. Kill and relaunch the app and verify if the site shield settings are retained

## Site hacks

- [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

- [x] Test that you can save an image from a site
- [x] Test that you are able to save a gif image

## Fullscreen

- [x] Test that entering HTML5 fullscreen works. And pressing restore to go back exits full screen. (youtube.com)

## Gestures

- [x] Verify zoom in / out gestures work on https://www.homedepot.com/
- [x] Verify that navigating to a different origin resets the zoom
- [x] Swipe back and forward to navigate, verify this works as expected

## Password Managers

- [x] Test tapping on 1Password on the slide-out keyboard launches 1Password App and able to select the stored credentials
- [x] Test tapping on bitwarden password manager in the autofill field launches the app and auto-fills the stored data

## Browser Lock

- [x] Test enabling browser pin settings asks for pin confirmation followed by reconfirm
- [x] Test swipe up/swipe down with browser in focus doesn't ask for pin confirmation
- [x] Test clicking on set pin asks for the pin to unlock before setting a new pin
- [x] Remove the app from memory and relaunch, enter a wrong pin, the browser should not be unlocked
- [x] Test cancel fingerprint confirmation shows enter pin window when fingerprint unlock is set up on the device

## Sync

- [x] Verify you are able to join sync chain by scanning the QR code
- [x] Verify you are able to join sync chain using code words
- [x] Verify you are able to create a sync chain on the device and add other devices to the chain via QR code/Codewords
- [x] Verify that bookmarks from other devices on the chain show up on the mobile device after sync completes
- [x] Verify newly created bookmarks get synced to all devices on the sync chain
- [x] Verify existing bookmarks before joining sync chain also gets sync'd to all devices on the sync chain
- [x] Verify sync works on an upgrade profile and new bookmarks added post-upgrade sync's across devices on the chain
- [x] Verify you can create a standalone sync chain with one device

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off or shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that block ad and unblock ad works on http://slashdot.org
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Test that clicking through a cert error in https://badssl.com/ works
- [x] Test that Safe Browsing works (https://www.raisegame.com/)
- [x] Turning Safe Browsing off and shields off both disable safe browsing for https://www.raisegame.com/
- [x] Enable block script globally from settings, Visit https://brianbondy.com/, nothing should load. Tap on Shields and disable block script, the page should load properly
- [x] Test that preferences default Bravery settings take effect on pages with no site settings
- [x] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [x] Test that turning on fingerprinting protection in preferences shows 1 fingerprint blocked at https://browserleaks.com/canvas . Test that turning it off in the Bravery menu shows 0 fingerprints blocked
  - [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on
  - [x] Test that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab
- [x] Load twitter and click on a tweet so the popup div shows. Click to dismiss and repeat with another div. Make sure it shows
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved.  Make sure the saved password is auto-populated when you visit the site again
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Test that PDF is loaded over https at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Test that PDF is loaded over HTTP at http://www.pdf995.com/samples/pdf.pdf
- [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)
- [x] Test that search results from https://startpage.com/ open in a new tab (due to target being _blank_)

## App linker

- [x] Long press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Background

- [x] Start loading a page, background the app, wait >5 sec, then bring to front, Verify splash screen is not shown

## Session storage

- [x] Test that tabs restore when closed, including active tab
