### ISSUE TITLE
UI Adjustments to NTP Credits

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2075]
### Description: 

Current UI:

<img width="584" alt="Screen Shot 2019-12-04 at 12 42 51 PM" src="https://user-images.githubusercontent.com/2781690/70192288-47610680-16c9-11ea-8b19-f6b09739819e.png">

Required changes:

- [x] Remove alert message and move the "View on <website>" into the actual website button.
- [x] Modify close button to be detached
- [x] Capitalize first letter of website (e.g. unsplash → Unsplash)

Like this:
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-04 at 19 01 46](https://user-images.githubusercontent.com/2781690/70192355-88f1b180-16c9-11ea-85ff-ad8f7e8072e4.png)
