### ISSUE TITLE
NTP Branded Backgrounds

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2151]
### Description: 

Branded NTP should be supported. This includes a lot of smaller tweaks as well:

- [x] Add image credit to the collection view so it does not cover favorites.
- [x] Landscape redesign
- [x] Remove background long-press
- [x] Remove sponsored background tap
- [x] Disable vertical bouncing
- [x] Landscape centering

Branded behavior:
- [x] Re-enabling (or disabling) background images should automatically re-enable (or disable) branded images.
- [x] When disabling Background Images in settings, all favorites and frequently visited sites are displayed as per pre-NTP background image.
- [x] No NTP branded images to be shown in private mode.
- [x] Fix pre-defined rotation of branded images (1 in 4)
- [x] Show branded image as second image
- [x] Pre-defined rotation of branded images
- [x] Brand overlay
- [x] Clicking brand → website
- [x] All rewards popups
