### ISSUE TITLE
Manual test run for 1.14.3 on iPad running iOS13

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2252]
## Per release speciality tests
 - [ ] NTP Branded Backgrounds. ([#2151](https://github.com/brave/brave-ios/issues/2151))
 - [x] Sample ad notification is not triggered when enabling rewards via sponsored image onboarding. ([#2237](https://github.com/brave/brave-ios/issues/2237))
 - [x] Learn more modal doesn't close other modals as well. ([#2243](https://github.com/brave/brave-ios/issues/2243))

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify saved password are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Bookmarks

- [x] Verify that creating a bookmark works
- [x] Verify that clicking a bookmark from bookmark manager loads the bookmark
- [x] Verify that deleting a bookmark works
- [x] Verify that creating a bookmark folder works
- [x] Verify that creating a bookmark inside the created folder works
- [x] Verify that you can add a bookmark directly inside a bookmark folder
- [x] Verify that you can delete a bookmark in edit mode
- [x] Verify that you can delete a bookmark folder with bookmarks inside
- [x] Verify adding a bookmark domain, subpaths is retained and you are successfully able to visit the domain subpath in a new tab

## Favourites

- [x] Verify editing favourite and changing URL updates the favicons accordingly
- [x] Verify that you can remove favourites
- [x] Verify that you can add new favourites from the share menu

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)
- [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

- [x] Verify search box is shown when selected via the share menu
- [x] Verify successful find
- [x] Verify forward and backward find navigation
- [x] Verify failed to find shows 0 results

## Private Mode

- [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list
- [x] Verify enabling `Private Browsing Only` shows warn message about sessions being lost in normal mode
- [x] Verify switching from `Private Browsing Only` to normal mode doesn't retain any sessions from before

## Reader Mode

- [x] Visit http://theverge.com, open any article, verify the reader mode icon is shown in the URL bar
- [x] Verify tapping on the reader mode icon opens the article in reader mode
- [x] Edit reader mode settings and open different pages in reader mode and verify if the setting is retained across each article

## History

- [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also, note if the progress bar activates and shows progress
- [x] Settings > Clear Private Data, and clear all. Check only the history is cleared and favourites are retained

## Shields Settings

- [x] Enable all switches in settings and visit a site and disable block scripts. Kill and relaunch the app and verify if the site shield settings are retained

## Site hacks

- [x] Verify https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

- [x] Verify that you can save an image from a site
- [x] Verify that you are able to save a gif image

## Fullscreen

- [x] Verify that entering HTML5 fullscreen works. And pressing restore to go back exits full screen. (youtube.com)

## Gestures

- [x] Verify zoom in / out gestures work on https://www.homedepot.com/
- [x] Verify that navigating to a different origin resets the zoom
- [x] Swipe back and forward to navigate, verify this works as expected

## Password Managers

- [x] Verify tapping on 1Password on the slide-out keyboard launches 1Password App and able to select the stored credentials
- [x] Verify tapping on bitwarden password manager in the autofill field launches the app and auto-fills the stored data

## Browser Lock

- [x] Verify enabling browser pin settings asks for pin confirmation followed by reconfirm
- [x] Verify swipe up/swipe down with browser in focus doesn't ask for pin confirmation
- [x] Verify clicking on set pin asks for the pin to unlock before setting a new pin
- [x] Remove the app from memory and relaunch, enter a wrong pin, the browser should not be unlocked
- [x] Verify cancel fingerprint confirmation shows enter pin window when fingerprint unlock is set up on the device

## Brave Rewards/Ads

- [x] Verify wallet is auto-created after enabling rewards
- [x] Verify account balance shows correct BAT and USD value
- [x] Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x] Verify grant details are shown in detailed view when a grant is claimed
- [x] Verify monthly budget shows correct BAT and USD value
- [x] Verify you can exclude a publisher from the auto-contribute table via left swipe
- [x] Verify you can exclude a publisher by using the toggle on the Rewards Panel
- [x] Verify you can remove excluded sites via `Restore All` button
- [x] Verify when you click on the BR panel while on a site, the panel displays site-specific information (site favicon, domain, attention %)
- [ ] Verify when you click on `Send a tip`, the custom tip banner displays
- [x] Verify you can make a one-time tip and they display in tips panel
- [x] Verify you can make a recurring tip and they display in tips panel
- [x] Verify you can tip a verified publisher
- [x] Verify you can tip a verified YouTube/Twitter/GitHub/Reddit creator
- [x] Verify tip panel shows a verified checkmark for a verified publisher/verified YouTube/Twitter/GitHub/Reddit creator
- [x] Verify tip panel shows a message about the unverified publisher
- [x] Verify BR panel shows the message about an unverified publisher
- [x] Verify you can perform a contribution
- [x] Verify if you disable auto-contribute you are still able to tip regular sites and YouTube/Twitter/Github creators
- [x] Verify that disabling Rewards and enabling it again does not lose state
- [x] Verify that disabling auto-contribute and enabling it again does not lose state
- [x] Verify disabling `Allow contribution to videos` option doesn't list any YouTube creator in ac list
- [x] Adjust min page time/visit in settings. Visit some sites and YouTube channels to verify they are added to the table after the specified settings
- [x] Verify you can `Hide Brave Rewards Icon` works and doesn't show rewards button when not enabled
- [x] Upgrade from an older version
  - [x] Verify the wallet balance (if available) is retained
  - [x] Verify auto-contribute list is not lost after upgrade
  - [x] Verify tips list is not lost after upgrade
  - [x] Verify wallet panel transactions list is not lost after upgrade
### Brave Ads
- [x] Verify ads is auto-enabled when rewards is enabled for the supported region
- [x] Verify ads are only shown when the app is being used
- [x] Verify ad notification are shown based on ads per hour setting
- [x] Verify clicking on an ad notification shows the landing page
- [x] Verify `view`,`clicked` and `landed` and `dismiss` states are logged based on the action

## Sync

- [x] Verify you are able to join sync chain by scanning the QR code
- [x] Verify you are able to join sync chain using code words
- [x] Verify you are able to create a sync chain on the device and add other devices to the chain via QR code/Codewords
- [x] Verify that bookmarks from other devices on the chain show up on the mobile device after sync completes
- [x] Verify newly created bookmarks get synced to all devices on the sync chain
- [x] Verify existing bookmarks before joining sync chain also gets sync'd to all devices on the sync chain
- [x] Verify sync works on an upgrade profile and new bookmarks added post-upgrade sync's across devices on the chain
- [x] Verify you can create a standalone sync chain with one device

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off or shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that block ad and unblock ad works on http://slashdot.org
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Verify that Safe Browsing works (https://www.raisegame.com/)
- [x] Turning Safe Browsing off and shields off both disable safe browsing for https://www.raisegame.com/
- [x] Enable block script globally from settings, Visit https://brianbondy.com/, nothing should load. Tap on Shields and disable block script, the page should load properly
- [x] Verify that preferences default Bravery settings take effect on pages with no site settings
- [x] Verify that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [x] Verify that turning on fingerprinting protection in preferences shows 1 fingerprint blocked at https://browserleaks.com/canvas . Verify that turning it off in the Bravery menu shows 0 fingerprints blocked
  - [x] Verify that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Verify that context menus work in the new twitter tab
- [x] Load twitter and click on a tweet so the popup div shows. Click to dismiss and repeat with another div. Make sure it shows
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved.  Make sure the saved password is auto-populated when you visit the site again
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Verify that PDF is loaded over https at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Verify that PDF is loaded over HTTP at http://www.pdf995.com/samples/pdf.pdf
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)
- [x] Verify that search results from https://startpage.com/ open in a new tab (due to target being _blank_)

## WebAuthn

- [x] Verify browser prompts for security key when trying to login to accounts 
- [x] Verify you are able to successfully authenticate an account using security key when prompted
- [x] Verify quickly connect and disconnect doesn't cause issue authenticating using security keys
- [x] Verify you are able to use security keys on both normal and private tabs
- [x] Verify you are able to use security keys to authenticate using NFC 

## App linker

- [x] Long press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Background

- [x] Start loading a page, background the app, wait >5 sec, then bring to front, Verify splash screen is not shown

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by kjozwiak** [comment]
Thanks for powering through these @LaurenWags 👍Finished the `WebAuthn` section.
