### ISSUE TITLE
Add translations for 1.15

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2341]

**Comment by srirambv** [comment]
Issues that need second verification 
- [x] https://github.com/brave/brave-ios/issues/2081
- [ ] https://github.com/brave/brave-ios/issues/2193
- [x] https://github.com/brave/brave-ios/issues/2300

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
- Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
