### ISSUE TITLE
Add ability to save PDF opened in Brave via share sheet menu

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3323]
### Description: 
Safari has this option:

![IMG_C9DABC041D5F-1](https://user-images.githubusercontent.com/6950387/108235337-04604700-7146-11eb-9b1e-57e3ff521327.jpeg)

### Steps to Reproduce 
  1. Open a pdf
  2. Open share menu

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Reported here
https://community.brave.com/t/how-to-download-a-pdf-file-on-iphone/207624

**Comment by balintbarna** [comment]
I'd say this is more of a bug, there's no way to download a PDF in brave. And there isn't even a share to safari option, so I have to go through the steps to open the same PDF in safari and then download it from there.

**Comment by RonanCodes** [comment]
In order to save the pdf locally I have to copy paste the link into Safari.

**Comment by mia1024** [comment]
This is especially problematic for any PDF that requires user login. So now to download the PDF I have to go to the same website on Safari, login to the website, go through 2FA, and then paste the same link just to get the PDF file. In addition, the print menu option doesn't seem to do anything.

**Comment by berndwa** [comment]
Any news about this?

**Comment by talondnb** [comment]
Looks like sharing to Dropbox app works so that’s a workaround I’m using for the moment.

**Comment by berndwa** [comment]
Why is this closed? PDF-Download still not works on iOS Brave or am I missing st?

**Comment by iccub** [comment]
@berndwa we close tickets once the code to fix it has been merged and is ready for the next release.
We hope to land it in Brave iOS 1.37

**Comment by berndwa** [comment]
Allright, thank you =)

> @berndwa we close tickets once the code to fix it has been merged and is ready for the next release.
> 
> We hope to land it in Brave iOS 1.37

**Comment by Uni-verse** [comment]
Verification Completed using `version 1.37 (22.3.29.15)`

Devices: 
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`

Test Plan: https://github.com/brave/brave-ios/pull/5053#issue-1158926171

- [x] Create PDF share sheet for reader mode
- [x] Create PDF share sheet for regular mode
- [x] Share site on reader mode
- [x] Share site on regular mode
- [x] Test sharing brave shield stats
- [x] Test sharing large PDF
- [x] Test emailing pdf

mobile 1 | mobile 2
-|-
![IMG_2559](https://user-images.githubusercontent.com/17885425/160943210-d4439f5b-7fd4-49b2-b0b7-6b2591e790ff.PNG) | ![IMG_2560](https://user-images.githubusercontent.com/17885425/160943219-ff342c1f-e798-4861-8317-87acfb37d25e.PNG)

Tablet
![IMG_0225](https://user-images.githubusercontent.com/17885425/161111670-9cf57aa0-f04a-489d-91d0-abeaea55f77b.PNG)
