### ISSUE TITLE
Investigate Brave talk audio video when app is background or tab is switched

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3760]
Currently when you switch tabs or lock the screen, audio stops working.
We have to see what can be done on iOS side and implement it if needed

**Comment by iccub** [comment]
Splitting to smaller tasks:

- [x] See if tab switching audio/video/microphone problem happens on other videocall websites
- [x] Check if not removing webview when tab is switched is a big performance hit.
- [x] See if locking the phone audio/video/microphone problem happens on other videocall websites.
- [x] See if we can do something about it, allow user to use BraveTalk when the app locked

**Comment by stephendonner** [comment]
# Verified `FIXED` using Brave for iOS version `1.29 (21.7.20.15)`, on iOS `14.7 (18G69)`.

## YouTube media

### Steps:
1. Go to `youtube.com` in Brave (not the dedicated app) and play a video.
2. Add a new tab via the `+` on the bottom toolbar, and load a mostly-text page.
3. Switch back and forth between the new tab and the original YouTube video.

**Confirmed the YouTube video kept playing without stopping or pausing.**

-----

## Brave Talk

### Steps:
1. loaded `talk.brave.com` on my MacBook Pro desktop.
2. entered `desktop` for a username and clicked on `Start video call`.
3. joined the call (`https://talk.brave.com/jInalpV3RpRz68dpmljDLCCFbpbKpt_XuUHWB7eOyRE`) via the iPhone, using Brave, with the username of `mobile`.
5. enabled microphone on `mobile`, and disabled it on `desktop`.
6. switched to a new tab on `mobile`.
7. **confirmed I still heard audio from the microphone coming from `mobile` through to `desktop`.**
8. enabled webcam on `mobile` and opened a new tab.
9. **confirmed I still saw myself on `desktop` from the `mobile` camera even with the Brave Talk tab on `mobile` inactive/backgrounded.**

**CAVEAT: this addresses _tabs_ within Brave; it doesn't address Brave-app-backgrounded or lockscreen uses.**
