### ISSUE TITLE
Search Overlay Issues

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3762]
- [x] In dark mode - Prompt to enable recent searches needs white text on "enable" button (currently displaying dark color which makes it hard to read)
- [ ] Maybe an issue: doesn't seem that all searches are being logged in recents.
- [x] Add 10px more spacing between bottom of favorites section and Recent search section in search overlay.
- [x] Move "On this page" directly below the search engine pre-search suggestions (should be above history/bookmarks)
- [x] "Clear" needs to have a confirmation action sheet pop up before clearing recents. No title just two buttons "Clear Recent" (destructive) and "Cancel"
- [ ] If possible add swipe-to-delete on individual "recents" rows.

**Comment by iccub** [comment]
Set release notes to `exclude` since the search overlay notes should happen in the main ticket https://github.com/brave/brave-ios/issues/3554 

cc @kjozwiak

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.17.10)
- Verified Enable button has text in white on dark mode
- Verified there is more spacing between favourites & recent searches
- Verified "On this page" is directly above history & bookmarks and below search suggestions
- Verified clear button shows a confirmation prompt before clearing the list

![image](https://user-images.githubusercontent.com/17010094/122528090-df0c1880-d013-11eb-93ba-c538ea2efc7f.png) | ![image](https://user-images.githubusercontent.com/17010094/122528122-e92e1700-d013-11eb-836d-461f3a553158.png) | ![image](https://user-images.githubusercontent.com/17010094/122528150-ef23f800-d013-11eb-8242-876ed8cdcb8a.png)
-- | -- | --

------------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.17.10)
- Verified Enable button has text in white on dark mode
- Verified there is more spacing between favourites & recent searches
- Verified "On this page" is directly above history & bookmarks and below search suggestions
- Verified clear button shows a confirmation prompt before clearing the list

![image](https://user-images.githubusercontent.com/17010094/122528270-07941280-d014-11eb-8be5-eefe6d72ac6c.png) | ![image](https://user-images.githubusercontent.com/17010094/122528383-28f4fe80-d014-11eb-9aa2-3194756f473e.png) | ![image](https://user-images.githubusercontent.com/17010094/122528233-fe0aaa80-d013-11eb-89cb-c8ae7eaac35f.png)
--  | -- | --

------------------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.17.10)
- Verified Enable button has text in white on dark mode
- Verified there is more spacing between favourites & recent searches
- Verified "On this page" is directly above history & bookmarks and below search suggestions
- Logged #3816 for crashing when trying to clear recent searches history

![image](https://user-images.githubusercontent.com/17010094/122528435-3b6f3800-d014-11eb-99b5-df471dc9faab.png) | ![image](https://user-images.githubusercontent.com/17010094/122528413-35795700-d014-11eb-9cb8-377a2cfc929f.png)
-- | --
