### ISSUE TITLE
Brave Playlist new add UX bugs

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4070]
- [x]  When long pressing a video we should show the old actionsheet menu vs using the url bar popover (some sites don't show the url bar button). And when adding from a long-press we should show the toast message that auto-hides.
- [x] When tapping Open in Brave Playlist we should start playback immediately vs needing to tap play button.
- [x] When a video is in the playlist we should hide the notification badge on the more button.

**Comment by iccub** [comment]
Issues have been addressed, closing it, main ticket is https://github.com/brave/brave-ios/pull/3977
