### ISSUE TITLE
Add initial set of iOS 14 Widgets

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4329]
We start with 3 widgets 

- [x] Favorites widget - will show list of user favorited websites.
- [x] Stats widget - will show blocked stats
- [x] Shortcuts widget - will have a few browser actions to choose from

**Comment by iccub** [comment]
Since we managed to restore old widgets code, i will finish it, i had to redesign one widget anyway.

**Comment by iccub** [comment]
reopened, code is merged but hidden temporarily

**Comment by soner-yuksel** [comment]
Closed due to [Issue-4582](https://github.com/brave/brave-ios/issues/4582) is closed and widgets restored back to project.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.34(22.1.4.19)
- Verified new widgets are available for Brave
- Verified able to add multiple widgets for the same app
- Verified clicking on the Stats widget launches the browser
- Verified clicking on the favourites widget launches the browser and loads the site from the favourites widget
- Verified clicking on empty tile on favourites widget launches the browser and focus on the active tab
- Verified able to edit the shortcuts widget to change items on the list 
- Verified clicking on the shortcut set on the widget, corresponding browser page is loaded 

Shortcuts Widget | Favourites Small | Favourites Big | Stats Small | Stats Big | Widget list | Edit widget | Edit Shortcuts | Edit Shortcut Selection
-- | -- | -- | -- | -- | -- | -- | -- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/148343418-de3bf6ab-6446-477f-9547-7412295ec24d.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343446-d10575e0-32d2-4d53-854e-91253690e0ad.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343466-58f6b474-2655-45e4-a8be-8beba59eca7f.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343634-bd8f0cd8-04b7-450f-83f9-7dce8494929a.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343654-6309d085-4836-4c16-94f3-5b36f73dfb6b.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343668-37f61c0b-1b24-40c8-80fc-8475cbe37e3f.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343688-8870307d-501f-4be1-9f2f-4c93de58f8da.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343725-d0d5e58c-0306-4da5-83d9-d65398f3067e.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148343742-f2a8d8df-6403-4c35-8da7-554c3dde3a46.png>

----------------------
Verification passed on iPhone XR with iOS 15.2 running 1.34(22.1.4.19)
- Verified new widgets are available for Brave
- Verified able to add multiple widgets for the same app
- Verified clicking on the Stats widget launches the browser
- Verified clicking on the favourites widget launches the browser and loads the site from the favourites widget
- Verified clicking on empty tile on favourites widget launches the browser and focus on the active tab
- Verified able to edit the shortcuts widget to change items on the list 
- Verified clicking on the shortcut set on the widget, corresponding browser page is loaded 

Shortcuts Widget | Favourites Small | Favourites Big | Stats Small | Stats Big | Widget list | Edit widget | Edit Shortcuts | Edit Shortcut Selection
-- | -- | -- | -- | -- | -- | -- | -- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/148342562-34600bf3-33fa-447a-b692-e753902d47a0.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342573-81198a5c-2872-4727-897f-37e8c4b94907.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342587-60f5b511-ce4c-4762-b18b-68072b722d01.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342603-a9e3cdc5-1061-47cd-876e-dfab69f847c7.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342613-e85080aa-742f-48aa-a37d-cbdce3b45a16.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342638-9d54dcac-7972-4f35-ab29-eea980d2e8da.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342653-fe8bf08b-a268-4e53-9bce-cf605af9836f.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342669-f9dcb392-221b-4772-841e-e0a1f17f3c8b.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148342684-a2233347-6370-4477-b866-ddcded4da557.png>

----------------------
Verification passed on iPad Pro with iOS 15.3 running 1.34(22.1.4.19)
- Verified new widgets are available for Brave
- Verified able to add multiple widgets for the same app
- Verified clicking on the Stats widget launches the browser
- Verified clicking on the favourites widget launches the browser and loads the site from the favourites widget
- Verified clicking on empty tile on favourites widget launches the browser and focus on the active tab
- Verified able to edit the shortcuts widget to change items on the list 
- Verified clicking on the shortcut set on the widget, corresponding browser page is loaded 

Shortcuts Widget | Favourites Small | Favourites Big | Stats Small | Stats Big | Widget list | Edit widget | Edit Shortcuts | Edit Shortcut Selection
-- | -- | -- | -- | -- | -- | -- | -- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/148338443-4a9b3444-b06c-4197-90f5-4835c0ce9a5e.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340737-5c504bb6-9a84-4c8e-bbcc-800b9086d36d.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148339104-e1a8ab78-3542-4ca4-9819-fdb16c0ed2f3.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340959-7a73d7d8-46e1-4191-9725-fe2d4dd357bd.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340996-bfd4a5c9-f212-40ef-9e80-78c9fc093ba6.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340775-7c72ecef-9f6e-45d8-84d6-a216240c7afb.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340790-bebd54da-d4a6-4e3f-97dd-dde3de1592b0.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340819-ed9a3cc5-0d9b-4ccc-9d97-3c42b4126da0.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/148340837-1d34dd81-a7af-47f1-9157-51baca511fdd.png>

----------------------
Encountered  #4807
