### ISSUE TITLE
Playlist - Ability to create folders 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4352]
### Description: 
Add the ability to create folders in Playlist, allowing users to organize their videos into groups within folders. 

Search GDrive for "Playlist Folder Sharing" for a spec

This issue is for the Folder Creation feature

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.8.21) BraveCore 1.36.108 (99.0.4844.51)`

PASSED on `iPad (7th Gen)` running `iOS 15.2.1`
PASSED on `iPhone 12 Pro` running `iOS 15.1.1`
PASSED on `iPhone X` running `iOS 14.4.2`

Test Plan: https://github.com/brave/brave-ios/pull/5003#issue-1143801037

- [x] install 1.35, add bunch of videos to playlist
- [x] Upgrade to 1.36, verify that videos are there in Saved folder
- [x] Verify CarPlay folders works
- [x] Verify Create, Edit (changing the folder name), Delete on folders work (Saved Folder is the only one that cannot do this).
- [x] Verify re-arranging/re-ordering folders works
- [x] Verify re-ordering items within a folder works
- [x] Verify moving items from one folder to another works
- [x] Verify empty folders show the empty state
- [x] Verify Playlist thumbnails show
- [x] Verify Long Press on a Folder to bring up context menu
- [x] Verify Long Press on a Playlist Item brings up context menu
- [x] Verify creating a folder with existing items, moves those items into the newly created folder
- [x] Verify cannot move items when only one folder exists
- [x] Verify cannot move item to the same folder that it's already in
- [x] Verify all of the above on iPad
- [x] Verify all of the above in Landscape
- [x] Verify the above while plugged into the Car and that the CarPlay updates when deleted from iPhone.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.3.1 running 1.36 (22.3.3.9) along with CarPlay
- Verified playlist folders are listed on CarPlay similar to how its shown in device

Device | CarPlay
-- | --
![image](https://user-images.githubusercontent.com/17010094/157194320-143cc827-7c8a-4991-a587-d1baf6b2b350.png) | ![image](https://user-images.githubusercontent.com/17010094/157215601-721bb5c7-2a6f-44b4-8f45-7a54cdd3dd8f.png)


- Verified playing a file saved under a custom folder is automatically loaded on CarPlay
- Verified able to move a playlist item from one folder to other while being connected to CarPlay
- Verified able to resume play when device is connected back
- Verified reordering the playlist items work while connected to CarPlay
- Verified able to reorder playlist folders while connected to CarPlay. CarPlay goes into root folder when this happens
- Verified able to delete items from folders when connected to CarPlay. CarPlay goes into root folder when this happens

Encountered https://github.com/brave/brave-ios/issues/5065, https://github.com/brave/brave-ios/issues/5066,  https://github.com/brave/brave-ios/issues/5067, https://github.com/brave/brave-ios/issues/5068, https://github.com/brave/brave-ios/issues/5069, https://github.com/brave/brave-ios/issues/5070, https://github.com/brave/brave-ios/issues/5071, https://github.com/brave/brave-ios/issues/5072
