### ISSUE TITLE
Replace action sheets with menus

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4440]
Menus are looking more modern, we can replace some of long press gestures that open action sheets and alerts with menus.

- [x] Long press menu on tabs toolbar button
- [x] Long press menu on `+` toolbar button.
- [x] Long press on address bar.
- [x] Long press on history item.
- [x] Long press on bookmark item.

**Comment by soner-yuksel** [comment]
The ticket description is updated with added screenshot and more details can be found in PR with screenshot.

**Comment by Uni-verse** [comment]
Verification completed on follow devices using build version `1.35 (22.1.14.22)`

**PASSED** - `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** -`iPad (7th Gen)` running `iPadOS 14.4.2`

https://github.com/brave/brave-ios/issues/4440#issue-1041082491

- Verified long press menu on tabs toolbar button.
- Verified long press menu on + toolbar button.
- Verified long press on address bar shows menu.
- Verified long press on history item shows menu.
- Verified long press on bookmark item shows menu.

Test Scenarios: 

- Navigating Bookmarks/History Screens
- Adding/Removing Bookmarks/History items
- Editing/Removing Bookmarks
- Removing History items
- History Search
- Bookmark Search
- Able to use the new menu items
- Private browsing mode

Note: Native share modal not being opened when selecting 'share link' from history/bookmark item menu.

iPhone UI: 
![IMG_2347](https://user-images.githubusercontent.com/17885425/150423790-c9665184-cfcc-43bb-a354-3436b76f4168.PNG)
![IMG_2343](https://user-images.githubusercontent.com/17885425/150423799-7aa6af1f-f62a-4569-96cd-d861a9b7293f.PNG)
![IMG_2344](https://user-images.githubusercontent.com/17885425/150423803-c41ef5bd-4d41-451f-bd8e-d5a80edcfd95.PNG)
![IMG_2345](https://user-images.githubusercontent.com/17885425/150423806-81de8bb5-6910-4d5f-8b04-99de80e347a4.PNG)
![IMG_2346](https://user-images.githubusercontent.com/17885425/150423810-6317d641-49c1-4f40-9a51-04c502967ef8.PNG)
