### ISSUE TITLE
NTP SI multiple simultaneous active campaigns

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#4706]
See https://github.com/brave/brave-browser/issues/19999 for desktop implementation/requirements

**Comment by jsecretan** [comment]
3 points for size

**Comment by petemill** [comment]
This can be tested or QA'ed via https://github.com/brave/ntp-si-assets/pull/885#issuecomment-1041148707

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.3.9) BraveCore 1.36.108 (99.0.4844.51)`

**PASSED** on `iPhone 12 Pro` | `iOS 15.1.1`
**PASSED** on `iPhone X` | `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` | `iPadOS 15.2.1`

Test Plan https://github.com/brave/ntp-si-assets/pull/885#issuecomment-1041148707

- [x] Verified observing red and blue on iOS devices.
- [x] Verified blue has different logo with "2".
- [x] Verified blue wraps after 4, red wraps after 3

iPhone | iPad
-|-
![IMG_2496](https://user-images.githubusercontent.com/17885425/157125265-14423691-4cdb-4874-9b03-a96805784c23.PNG) | ![Screen Shot 2022-03-07 at 1 56 52 PM](https://user-images.githubusercontent.com/17885425/157125275-e64329c6-ff1f-41e4-ac91-0787223fb4e2.png)
