### ISSUE TITLE
Remove SwiftUI workarounds for iOS 14 release build crash (`FB9812596`)

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5297]
### Description: 

Xcode 13.3 and higher no longer reproduce the crash when running availability checks for iOS 15 APIs on iOS 14 devices so we can remove the workarounds as we are using 13.3.1 for submitting to App Store

### Test Cases

We should ensure the app does not crash on iOS 14 in the following places:
- Brave Wallet portfolio & asset details (graph)
- Brave Wallet asset list (searching)
- Brave Wallet settings > custom networks (swipe to delete)
- Brave Wallet edit user assets (swipe to delete)
- Settings > Brave Shields & Privacy > Manage Website Data (swipe to delete)

These crashes would occur immediately upon viewing the screen and not specifically when performing the action

**Comment by Uni-verse** [comment]
Verified using 1.39 (22.5.30.17) 

Test Devices: 
iPhone X running iOS 14.4.2 
iPhone 12 Pro running iOS 15.4
iPad running IOS 15.5

- Verified no crashes were observed while checking sections below

- [x] Brave Wallet portfolio & asset details (graph)
- [x] Brave Wallet asset list (searching)
- [x] Brave Wallet settings > custom networks (swipe to delete)
- [x] Brave Wallet edit user assets (swipe to delete)
- [x] Settings > Brave Shields & Privacy > Manage Website Data (swipe to delete)

Porfolio/Graph | User Asset Search | Search | Manage Data
-|-|-|-
![IMG_2675](https://user-images.githubusercontent.com/17885425/171307264-55713eb4-83c6-4caa-8377-671fbd5d600d.PNG) | ![IMG_2676](https://user-images.githubusercontent.com/17885425/171307266-12189021-1d38-4cda-8f68-c5c22e8966e3.PNG) | ![IMG_2680](https://user-images.githubusercontent.com/17885425/171307267-1c6dcca3-74dc-41a3-9cff-ae265e0ce6a7.PNG) | ![IMG_2681](https://user-images.githubusercontent.com/17885425/171307270-686b5b51-7052-407e-831e-69deaf9992a7.PNG)


---------
Verification passed on iPhone 7+ with iOS 14.8.1 
- Verified steps from issue description
- Verified no crash either while opening the mentioned screens or while performing any action on those said screens
