### ISSUE TITLE
Add support for Dynamic Type on the URL bar & toolbar

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5683]
### Description: 

This is an issue that outlines a small subset of the full dynamic type support issue (#1344)

This should add dynamic font + image sizes on the URL bar, tab bar and toolbar

## Test Plan

- Test that toolbar buttons scale at Large, XL and XXL and get no bigger after
- Test landscape + iPad to ensure bottom toolbar buttons that end up in the top toolbar behave the same
- Test various extra URL bar buttons: playlist, reader mode, wallet, rewards behave the same
- Test that various onboarding popovers that highlight elements in the URL bar look correct
- Test that URL bar text scales until Accessibility Large and no more after
- Test that the collapsed URL bar does the same
- Test that the tab titles in the tab bar scale until XXL and no further

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.8.19)`

Test Devices:

iPhone XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

**Toolbar buttons**

- [x] Ensured toolbar buttons scale dynamics and get no bigger after XXL
- [x] Ensured button scale is limited to XXL in both orientations

**Landscape + iPad (top toolbar buttons)**

- [x] Ensured toolbar buttons in the top toolbar behave the same
- [x] Ensured toolbar buttons on ipad behave the same

**Various extra URL bar buttons: playlist, reader mode, wallet, rewards behave the same**

- [x] Confirmed URL bar buttons are working normally

**Various onboarding popovers that highlight elements in the URL bar look correct**

- [x] Confirmed onboarding popovers

Issue - default onboarding button text ui issue. 

**URL bar text scales until Accessibility Large and no more after**

- [x] Confirmed URL text scales until Accessibility Large 

Issue - text scales more than accessibility large

**Collapased URL bar**

- [x] Collapsed URL bar behaves the same way

**Tab titles in the tab bar scale until XXL and no further**

- [x] Confirmed tab bar scales until XXL

1 | 2
-|-
![IMG_0503](https://user-images.githubusercontent.com/17885425/183990779-60754c37-a7c8-4211-9eec-74cc54a09ebc.PNG) | ![IMG_0015](https://user-images.githubusercontent.com/17885425/183992122-d58a5f36-d6f2-4280-85c5-e8d4084d5000.PNG)
