### ISSUE TITLE
News Customization Revamp

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6426]
### Description: 

This is a blanket issue around the new settings UI for the Brave News revamp

List of specs around the new settings revamp:
- `Brave News sources spec`
- `Customize Brave News spec`
- `Brave News 2.0 Migration spec`
- `Source Suggestion For Brave News`

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.6.11)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2
iPad - iOS 16.x

### Clean Profile 

<details><summary>Case: Fresh Profile - Top Sources</summary>

- Ensured Top Sources are enabled on fresh profile 
- Ensured that articles are shown in the feed pertaining to top sources

Example | Example
-|-
![IMG_4170](https://user-images.githubusercontent.com/17885425/206004670-6dddaf81-4ba0-4069-a565-47301e8dceaf.PNG) | ![IMG_4171](https://user-images.githubusercontent.com/17885425/206004683-e9b28f66-8538-4265-b5a1-f66b7ee1a2d4.PNG)
![IMG_0813](https://user-images.githubusercontent.com/17885425/206004736-4ff14069-7842-46e6-8564-0a2cf0e0c430.PNG) | ![IMG_0814](https://user-images.githubusercontent.com/17885425/206004743-a26a24f9-802c-4214-a90a-f4cffb131267.PNG)

</details> 

<details><summary>Case: UI / Figma</summary>

- Ensured that UI matches the figma designs for iOS

Example | Example
-|-
![IMG_4174](https://user-images.githubusercontent.com/17885425/206006326-96cb247a-dae5-4c1f-becc-c7ceae3ce071.PNG) | ![IMG_4175](https://user-images.githubusercontent.com/17885425/206006332-180e5672-4fad-47dc-a777-fbe83b48cb1f.PNG)
![IMG_0817](https://user-images.githubusercontent.com/17885425/206006494-962361a3-c2ae-487a-b661-0f48a7edb81b.PNG) | ![IMG_0819](https://user-images.githubusercontent.com/17885425/206006501-f469fc9d-7792-454f-8169-957ab6408c09.PNG)

</details>
 
<details><summary>Case: Enabling from NTP, menu</summary>

- Verified Brave News can be enabled from NTP onboarding
- Verified Brave News can be enabled from the Settings -> Brave News

Example | Example
-|-
![IMG_0821](https://user-images.githubusercontent.com/17885425/206012629-a170fde1-79c6-4593-b52c-cd240a2a43f8.PNG) | ![IMG_0822](https://user-images.githubusercontent.com/17885425/206012643-344ea361-54a0-4166-8d52-801099d8b9ee.PNG)

</details>

<details><summary>Case: Search in brave news settings</summary>

- Verified using searching in brave news settings on NTP as well as settings in the hamburger menu
- Verified results are displayed 

Example | Example
-|-
![IMG_4178](https://user-images.githubusercontent.com/17885425/206014932-4aa0ffd7-a7f4-4fa7-b529-d68e01340cd8.PNG) | ![IMG_4179](https://user-images.githubusercontent.com/17885425/206014942-986bcd5c-1b6f-4dbd-a50a-549ce2e0f6fe.PNG)

</details>

<details><summary>Case: Following sources/channels and suggestions</summary>

- Verified following new sources will display them in the `Following` page on index page
- Verified disabling sources in feed using the long press context menu will remove source from `Following` page
- Verified tapping on source will display `Follow` or `Unfollow`
- Verified relaunch the app will retain the news state
- Verified custom RSS feeds will show up in the `Following` page

![IMG_4175](https://user-images.githubusercontent.com/17885425/206018271-636224fa-82e3-4085-acf6-71d418c39108.PNG)

</details>

<details><summary>Case: Disabling all sources</summary>

- Verified we present a banner if all sources are disabled
- Tapping on `Sources & Settings` will open the news settings page

Example | Example
-|-
![IMG_0807](https://user-images.githubusercontent.com/17885425/206008819-783788f5-dec6-4de2-90d4-5844e80b8c6f.PNG) | ![IMG_4168](https://user-images.githubusercontent.com/17885425/206008864-6e2d2526-4b35-4733-bbca-1f1d8fe81c1c.PNG)

</details>

<details><summary>Case: Adding custom RSS feed</summary>

- Verified adding RSS feed using the search field as well as using `Add News Source` from the shared menu on blogs

Example | Example
-|-
![IMG_4175](https://user-images.githubusercontent.com/17885425/206009833-1833ec12-8df8-44b2-bf72-fa0679249542.PNG) | ![IMG_4177](https://user-images.githubusercontent.com/17885425/206009858-3e4f2613-4b71-4bf8-9fcc-97d8076eb738.PNG)

</details>

<details><summary>Case: Disabling sources in feed with long press</summary>

- Verified using long press to enable/disable source in feed
- Verified source is not followed after disabling 

Example | Example
-|-
![IMG_4176](https://user-images.githubusercontent.com/17885425/206010260-7c67be55-b42d-4e7a-85cd-76cec0585682.PNG) | ![IMG_0812](https://user-images.githubusercontent.com/17885425/206010299-502fca36-90cf-4289-8c3d-bee2b942ca00.PNG)

</details>

<details><summary>Case: Relaunching app</summary>

- Verified relaunch app doesn't change new sources, brave news state

</details>

<details><summary>Case: Inline Ads, loading ads</summary>

- Verified inline ads are showing up in brave news feed
- Ensured user is able to load the ads in private/normal tabs
 
 Example | Example
 -|-
![IMG_4173](https://user-images.githubusercontent.com/17885425/206013068-964e8473-3d50-4e6b-9388-9e8beed4c464.PNG) | ![IMG_0815](https://user-images.githubusercontent.com/17885425/206013107-39dac878-d728-4823-b8ff-a41ca476d929.PNG)

</details>

<details><summary>Case: Brave news in JP region</summary>

- Verified client is using JP source list for news

Example | Example
-|-
![IMG_4162](https://user-images.githubusercontent.com/17885425/206010939-ba5aa3c5-96b7-4885-bfe7-9f03b9ac80fb.PNG) | ![IMG_4163](https://user-images.githubusercontent.com/17885425/206010988-7d5343ec-2ada-4453-a19a-6163315138a2.PNG)

</details>

<details><summary>Case: Brave news in ES region</summary>

Example | Example
-|-
![IMG_4165](https://user-images.githubusercontent.com/17885425/206011964-2cf618d1-7d77-4741-9a53-5f0eed6aeeb3.PNG) | ![IMG_4166](https://user-images.githubusercontent.com/17885425/206011978-49714666-4474-4755-8258-918a156b30d3.PNG)

</details>

### Upgraded Profile 

<details><summary>Case: Profile w/ news off</summary>

1. Install 1.45.2
2. Launch app but do not opt into Brave News
3. Upgrade to 1.46.x

- Confirmed Brave news is disabled and onboarding is present on upgraded profile
- Confirmed user is able to enable brave news on upgraded profile

![IMG_0820](https://user-images.githubusercontent.com/17885425/206021926-dc856ea0-a3f1-47f9-8178-4b89286327dd.PNG)

</details>

<details><summary>Case: Profile w/ news off/dismissed</summary>

1. Install 1.45.2
2. Launch app but do not opt into Brave News, dismiss onboarding banner
3. Upgrade to 1.46.x

- Confirmed Brave News onboarding is not shown on NTP
- Confirmed navigating to settings -> Brave News will display the onboarding screen
- Confirmed enabling Brave news will show the feed

Example | Example
-|-
![IMG_0823](https://user-images.githubusercontent.com/17885425/206021187-9aaf20ab-cb0d-4342-b213-8d1fdb01e04e.PNG) | ![IMG_0824](https://user-images.githubusercontent.com/17885425/206021121-31a4bce3-1ccc-4e8a-8062-813ffeded688.PNG) | ![IMG_0825](https://user-images.githubusercontent.com/17885425/206021158-5d418802-ce81-4f86-9dd1-667b55280d3a.PNG)

</details>

<details><summary>Case: Profile w/ news on</summary>

1. Install 1.45.2
2. Launch app and opt into Brave news, confirm news feed is displayed
3. Upgrade to 1.46.x

- Verified Brave news is enabled
- Verified Onboarding is not shown on upgraded profile
- Verified `Top Sources` source is followed/enabled

![IMG_0813](https://user-images.githubusercontent.com/17885425/206023485-244c7a4c-47b3-4f3a-a490-18850aeb8d9a.PNG)

</details>

<details><summary>Case: Profile w/ news on and RSS/sources customization</summary>

1. Install 1.45.2
2. Launch app and opt into Brave news, confirm news feed is displayed
3. Add custom RSS feeds
4. Enable sources that were not enabled by default
5. Upgrade to 1.46.x

- Verified Brave news is enabled
- Verified Onboarding is not shown on upgraded profile
- Verified `Top Sources` source is followed/enabled
- Verified enabled sources from previous version are retained and displayed in `Following` Page

![IMG_4175](https://user-images.githubusercontent.com/17885425/206024570-2b06b6f1-819c-49ce-9bc7-e951a6c29462.PNG)

</details>

Misc. Post Upgrade Tests

- [x] Case: Adding RSS after upgrading
- [x] Case: Changing preferences after upgrading
- [x] Case: Disabling news after upgrading
- [x] Case: Re-enabling news after disabling doesnt lose sources/state
