### ISSUE TITLE
Cannot connect to iOS sync chain code

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6456]
### Description: 

Devices having problems while connecting to sync chain when trying to scan code from iOS device (Android). Able to scan sync code from desktop client.

To solve this problem Android devices are having, we are asked to make the QR code bigger in size.

### Steps to Reproduce 
   1. Install 1.45 on Android device
   2. Install 1.45 on iOS device
   3. Start a sync chain on iOS device
   4. Select `add a device` on the IOS device
   5. Begin sync flow on Android device, attempt to scan a sync code on the iOS device with the camera

**Actual result:** 

Sync code not recognized 

**Expected result:**

After scanning QR code, user should be prompted to proceed to connect to sync chain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.45

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` on the following devices:

iOS: 

iPad (7th Gen) - iPadOS 16.x
iPhone XR - iOS 15.x

Android: 

Samsung GS 21 - Android 12
Samsung Tab S7 - Android 12

1. Install nightly build on Android 
2. Install 1.46 build on iOS
3. Create sync chain on iOS
4. Scan sync code on Android device using camera

- Unable to recognize sync code on Android device when scanning. 
- Logged follow up issue https://github.com/brave/brave-ios/issues/6657

**Comment by Uni-verse** [comment]
@soner-yuksel its not working on the Android devices listed. Created follow up issue to close this one since its not a blocker. 

CC: @iccub @AlexeyBarabash @kjozwiak

**Comment by soner-yuksel** [comment]
@Uni-verse Are these all the devices you can test or does the scanning work for other brands/models ? cc @Brandon-T

**Comment by AlexeyBarabash** [comment]
@soner-yuksel 
I tried on the screenshot which @Uni-verse provided with new QR code with my Samsung S22 and Google Pixel 6. Somehow they both refused to scan that QR code, even third-party QR scanner.

The changed QR image looks much better than it was before - area is bigger and the dots are not as tiny as they were before. I thought that it was the reason of the failure and requested to change that, but it looks the problem is in something other.

**Comment by soner-yuksel** [comment]
@AlexeyBarabash  I am not sure what is happening here tbh, I dont have an Android device but @Brandon-T tested this change with his Google Pixel etc and it works great for him.

**Comment by AlexeyBarabash** [comment]
Samsung Camera App can scan that QR code.

**Comment by AlexeyBarabash** [comment]
@soner-yuksel 

Just tried to see how it works with brave-ios running on the emulator.
1. Works fine on default iPhone 14 Pro - I can scan and I can connect.
2. There is layout issue on iPhone 13 SE - I can't scan/connect
<img width="446" alt="Screenshot 2022-12-22 at 05 07 11" src="https://user-images.githubusercontent.com/24739341/209048376-aef2240e-ddf3-42b5-ba55-57758677b677.png">
3. iPad Pro 12.9-inch, the similar to one used by @Uni-verse  - works fine, I can connect/scan
4. iPad Pro 12.9-inch **in dark mode** doesn't work - I cannot scan the QR code




So I believe that this is the reason of the issue. If we compare desktop vs iOS both in dark mode, we will see that QR code on desktop has white border, and on iOS it doesn't:

Desktop
<img width="507" alt="Screenshot 2022-12-22 at 05 29 55" src="https://user-images.githubusercontent.com/24739341/209050934-9a98df14-8be3-466c-8e9d-57f1c8026f50.png">

iOS
<img width="232" alt="Screenshot 2022-12-22 at 05 30 48" src="https://user-images.githubusercontent.com/24739341/209050943-308e86c0-edb9-4810-8134-4e71a3ec04e7.png">

 As a summary there are two things to fix:
- [ ]  1. Layout on small screen sizes
- [ ]  2. Add white border around QR code image which is always white even when dark mode is activated

I hope this is the reason.

**Comment by soner-yuksel** [comment]
@AlexeyBarabash thanks for checking in detail, I will fix the layout issue, I believe I introduced it while trying to make change here. @Uni-verse already created ticket for it.

And I will also try adding the white frame around and if it doesnt help I will try removing the lion logo and figure out what is working.

So steps:

 

- [x] 1. Layout on small screen sizes
- [x] 2. Add white border around QR code image which is always white even when dark mode is activated
- [x] 3. Set the parameter renderLogoInCenter false and try

**Comment by soner-yuksel** [comment]
@AlexeyBarabash The problems we mentioned is fixed and I tagged you for the PR https://github.com/brave/brave-ios/pull/6708.

Thank you for checking in detail I hope this time, we will achieve the clear result
