### ISSUE TITLE
No Articles displayed after unfollowing top news source

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6566]
### Description: 
No Articles displayed after unfollowing top news source even if following other sources

Use Cases: 

- Disabling Top Sources with other sources enabled/followed
- Disabling Top Sources and then re-enabling Top Sources 
- Disabling Top Sources and then following other sources afterwards

### Steps to Reproduce 
  1. Install 1.46
  2. Enable Brave News
  3. Open News settings
  4. Follow some sources 
  5. Unfollow `Top Sources` under `Channels`
  6. Reload NTP

**Actual result:** 
No Articles to show banner is displayed

Example | Example
-|-
![IMG_4168](https://user-images.githubusercontent.com/17885425/205975887-b466372a-afe9-4d05-9e31-179a9aa787af.PNG) | ![IMG_0807](https://user-images.githubusercontent.com/17885425/205976046-9357a282-ee93-40f9-9926-5de39fb5c9c1.PNG) | 

**Expected result:**
News feed should be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.46.x

**Device details:** 
iPhone, iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.11.6.19)` on the following device(s):

iPhone 12 - IOS 16.x
iPhone XR - iOS 15.x
iPad - iPadOS 16.x
iPhone X - iOS 14.x

Using STR in https://github.com/brave/brave-ios/issues/6566#issue-1479645427 checked all of the use cases mentioned.

- Verified Articles are displayed when top sources are disabled.

- [x] Disabling Top Sources with other sources enabled/followed
- [x] Disabling Top Sources and then re-enabling Top Sources
- [x] Disabling Top Sources and then following other sources afterwards
