### ISSUE TITLE
Refactor News card generation for testability

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6691]
### Description: 

We should add tests for the card generation aspect of Brave News but this will require refactoring it out of the main `FeedDataSource`

### Test Case

Sanity test Brave News

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.47 (23.1.17.15)`

- Tested functionality / use cases below as part of the Sanity Test. 
- [x] Ensured onboarding flow works and brave news card is displayed on fresh profile. 
- [x] Ensured NTP brave news card is displayed as well as opt in card in menu > settings > Brave News
- [x] Ensured user is following top sources by default
- [x] Ensured news feed is shown after opting into brave news. Ensured scrolling through the news feed is smooth and cards are rendered correctly
- [x] Ensured news feed card ordering in default settings and when adding sources from multiple regions
- [x] Ensured following/unfollowing sources, channels, suggestions will update the feed accordingly
- [x] Ensured unfollowing all sources will display no sources modal in the NTP
- [x] Ensured user is able to add custom RSS source
- [x] Ensured hiding content via context menu works
- [x] Ensured opening sources in new tabs
- [x] Ensured source preferences are retained on upgraded profile (1.46.2 -> 1.47)

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_0269](https://user-images.githubusercontent.com/17885425/213242452-90bb47d3-89e7-40cc-b35f-0647c4e7fb74.PNG) | ![IMG_0264 2](https://user-images.githubusercontent.com/17885425/213242581-a6fa33ef-a9cb-4259-abc7-23125049ce01.PNG) | ![IMG_0265 2](https://user-images.githubusercontent.com/17885425/213242608-c0be3c88-c733-4b14-a78e-3cb515d58dc6.PNG) | ![IMG_0266 2](https://user-images.githubusercontent.com/17885425/213242625-a3150ba1-63dc-458a-99fd-3de57b5c7698.PNG) | ![IMG_0267 2](https://user-images.githubusercontent.com/17885425/213242631-4510653c-63dd-45af-9b01-4ec7653c8f54.PNG) | ![IMG_0268 2](https://user-images.githubusercontent.com/17885425/213242635-c89a56c6-3e4a-43d9-9493-b2c55f0b8f4f.PNG) | ![IMG_0262 2](https://user-images.githubusercontent.com/17885425/213246142-38132940-bf68-4122-a50f-eee09d34d89d.PNG)
