### ISSUE TITLE
[iOS] Rewards: Remove "wallet" language from Rewards Internals

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-ios#7221]
## Description

In Brave Rewards > Rewards Internals, remove all instances of the word "Wallet". Instead, the new language is "Rewards" or "profile". For example:

```[tasklist]
### Tasks
- [ ] WALLET INFO --> REWARDS PROFILE INFO
- [ ] Wallet Payment ID --> Rewards Payment ID
- [ ] Wallet Creation Date --> Rewards Profile Creation Date
```

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1` using `1.51 (23.4.28.18)`

- Ensured section header is changed from `WALLET INFO` to `REWARDS PROFILE INFO` on Rewards Internals page
- Ensured `Wallet Payment ID` is changed to `Rewards Payment ID`
- Ensured `Wallet Profile Creation Date` is changed to `Rewards Profile Creation Date`
- Ensured JSON has updated copies when exporting rewards internals report

Example | Example | Example
-|-|-
![IMG_3101](https://user-images.githubusercontent.com/17885425/236318353-3019f398-e83f-4218-9ff2-761a756eb679.PNG) | ![IMG_0232 3](https://user-images.githubusercontent.com/17885425/236318369-67523747-ad44-40b7-9828-7e0a09994657.PNG) | ![IMG_3102](https://user-images.githubusercontent.com/17885425/236318935-9393c8f6-82c2-44a2-889c-1dcf4d827fa0.PNG)
