### ISSUE TITLE
Manual test run for iOS12 iPhone 6 for 1.7.2

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#730]
## Per release speciality tests
 - [x] Tabs bar shown when a favourite is loaded after deleting browser data. ([#591](https://github.com/brave/brave-ios/issues/591))
 - [x] Partner search + Browser lock popup appear on settings after turning on "Private Browsing Only" mode. ([#637](https://github.com/brave/brave-ios/issues/637))
 - [x] Re-enable HTTPSE UI. ([#653](https://github.com/brave/brave-ios/issues/653))
 - [x] Saving a GIF doesn't work (Saves as still image). ([#659](https://github.com/brave/brave-ios/issues/659))
 - [x] Can't move bookmarks inside of a folder. ([#687](https://github.com/brave/brave-ios/issues/687))
 - [x] HTTPSE Shield Setting → Scheme Independent. ([#688](https://github.com/brave/brave-ios/issues/688))

## Installer

- [ ] Check that installer is close to the size of last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Make sure that data from the last version appears in the new version OK
- [x] Test that the previous version's cookies are preserved in the next version
- [x] Test that saved passwords are retained upon upgrade
- [x] Ensure stats are retained when upgrading from previous version
- [x] Ensure per site settings are retained when upgrading from previous version

## Bookmarks

- [x] Test that creating a bookmark in the left well works
- [x] Test that clicking a bookmark in the left well loads the bookmark
- [x] Test that deleting a bookmark in the left well works
- [x] Test that creating a bookmark folder works
- [x] Test that creating a bookmark inside the created folder works
- [x] Test that you are able to add a bookmark directly inside a bookmark folder
- [x] Test that you are able to delete a bookmark in edit mode
- [x] Test that you are able to delete a bookmark folder with bookmarks inside
- [x] Test adding a bookmark domain subpaths is retained and you are successfully able to visit the domain subpath in a new tab

## Favourites

- [x] Test editing favourite and chaning URL updates the favicons accordingly
- [x] Test that you are able to remove favourites
- [x] Test that you are able to add new favourites from share menu

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)
- [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Find on page

- [x] Ensure search box is shown when selected via the share menu
- [x] Test successful find
- [x] Test forward and backward find navigation
- [x] Test failed find shows 0 results

## Private Mode

- [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

## Reader Mode
- [x] Visit http://theverge.com, open any article, verify the reader mode icon is shown in the URL bar
- [x] Verify tapping on the reader mode icon opens the article in reader mode
- [x] Edit reader mode settings and open different pages in reader mode and verify if the setting is retained across each article

## History

- [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress
- [x] Settings > Clear Private Data, and clear all. Check history is cleared and none of the favourites are cleared

## Shields Settings

- [x] Enable all switches in settings and visit a site and disable block scripts. Kill and relaunch app and verify if the site shield settings are retained

## Site hacks

- [x] Test https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Downloads

- [x] Test that you can save an image from a site
- [x] Test that you are able to save a gif image

## Fullscreen

- [x] Test that entering HTML5 full screen works. And pressing restore to go back exits full screen. (youtube.com)

## Gestures

- [x] Test zoom in / out gestures work
- [x] Test that navigating to a different origin resets the zoom
- [x] Swipe back and forward to navigate, verify this works as expected

## Password Managers

- [x] Test tapping on 1Password on the slide out keyboard launches 1Password App and able to select the stored credentials
- [ ] Test tapping on bitwarden password manager in the autofill field launches the app and autofills the stored data

## Browser Lock

- [x] Test enabling browser pin settings asks for pin confirmation followed by reconfirm
- [x] Test swipe up/swip down with browser in focus doesn't ask for pin confirmation
- [x] Test clicking on set pin asks for pin to unlock before setting a new pin
- [x] Remove app from memory and relaunch, enter wrong pin, browser should not be unlocked
- [x] Test cancel fingerprint confirmation shows enter pin window when fingerprint unlock is setup on device

## Sync

- [ ] Ensure you are able to scan the QR code and sync with laptop
- [ ] Ensure the bookmarks from laptop shows up on the mobile after sync completes
- [ ] Add a bookmark on mobile and check if it gets synced to the laptop

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that block ad and unblock ad works on http://slashdot.org
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Test that clicking through a cert error in https://badssl.com/ works
- [x] Test that Safe Browsing works (https://www.raisegame.com/)
- [x] Turning Safe Browsing off and shields off both disable safe browsing for https://www.raisegame.com/
- [x] Enable block script globally from settings, Visit https://brianbondy.com/, nothing should load. Tap on Shields and disable block script, page should load properly
- [x] Test that preferences default Bravery settings take effect on pages with no site settings
- [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [x] Test that turning on fingerprinting protection in preferences shows 1 fingerprints blocked at https://browserleaks.com/canvas . Test that turning it off in the Bravery menu shows 0 fingerprints blocked
  - [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on
  - [x] Test that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Test that context menus work in the new twitter tab
- [x] Load twitter and click on a tweet so the popup div shows. Click to dismiss and repeat with another div. Make sure it shows
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved.  Make sure the saved password is auto-populated when you visit the site again
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Test that PDF is loaded over https at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Test that PDF is loaded over http at http://www.pdf995.com/samples/pdf.pdf
- [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)
- [x] Test that search results from https://startpage.com/ opens in a new tab (due to target being _blank)

## App linker

- [x] Long press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Background

- [x] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

## Session storage

- [x] Test that tabs restore when closed, including active tab

**Comment by srirambv** [comment]
Looks good on iPhone 6.

**Comment by btlechowski** [comment]
Looks good on iPhone SE. I went through whole testrun.
