### ISSUE TITLE
Implement Brave Ads rotating hash

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#7570]
Rotating hash should be sent in the payload when sending ad events, i.e. spending confirmation tokens. Implemented in https://github.com/brave/brave-browser/issues/29084

**Comment by kylehickinson** [comment]
Fixed by https://github.com/brave/brave-ios/pull/7344

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPhone XR` running `iOS 15.5` on release, beta, dev channels using version `1.52 (23.6.22.18)`

**Acceptance Criteria**: https://github.com/brave/brave-core/pull/18278#issue-1686838173

- [x] `rotating_hash` sent in payload request
- [x] hash value based on timestamp per `creativeinstanceid`
- [x] Same `rotating_hash` used across all channels (release, beta, dev) per `creativeinstanceid` per hour
- [x] Different `rotating_hash` value on different device for the same `creativestanceid` per that same hour
- [x] `rotating_hash` has the same value for all of the confirmation events per `createinstanceid`

<hr>

**Scenario 1:** `"creativeInstanceId": "dcdb9706-d0c4-47bc-9dff-c51dcb4fbf3e"` 

- Verified `rotating_hash` is appended to the request in `anonymous.ads.brave.com`
- Verified `rotating_hash` value changes on the hour for the same creativeinstance (same device)
- Verified hash value is same across all channels

![Screenshot 2023-06-23 at 12 20 37 PM](https://github.com/brave/brave-ios/assets/17885425/0f20c7c8-212e-4b83-becb-f1117160c6dd)


2023-06-23T18:00:00.000Z (Hour 1)

Release | Beta | Dev
-|-|-
![Screenshot 2023-06-23 at 2 17 46 PM](https://github.com/brave/brave-ios/assets/17885425/959cf023-b3d0-4c2b-b048-2a77615798dd) | ![Screenshot 2023-06-23 at 2 24 41 PM](https://github.com/brave/brave-ios/assets/17885425/b672fbb0-af8e-474d-868e-a977f38de15a) | ![Screenshot 2023-06-23 at 2 25 01 PM](https://github.com/brave/brave-ios/assets/17885425/becec946-2b09-4b84-9552-441b0ec6124c)

2023-06-23T19:00:00.000Z (Hour 2)

Release | Beta | Dev
-|-|-
![Screenshot 2023-06-23 at 3 19 23 PM](https://github.com/brave/brave-ios/assets/17885425/956d4495-8623-4bae-8406-254c9c6d159a) | ![Screenshot 2023-06-23 at 3 14 40 PM](https://github.com/brave/brave-ios/assets/17885425/1d50e1d3-8fc3-466a-862e-91da4c1429cd) | N/A

**Scenario 2:** `"creativeInstanceId": "3dab56ea-ea78-4a46-8eaa-fcfb4d45ee8a"`

- Verified rotating_hash value is different on different device for the same `creativestanceid`

2023-06-23T19:00:00.000Z, Device A

Beta | Dev
-|-
![Screenshot 2023-06-23 at 3 21 19 PM](https://github.com/brave/brave-ios/assets/17885425/277a6b04-8546-40f5-88b5-43e28c1a870d) | ![Screenshot 2023-06-23 at 3 21 29 PM](https://github.com/brave/brave-ios/assets/17885425/7946d7c3-b89d-4fdd-94fd-9e19fa7efd3e)

2023-06-23T19:00:00.000Z, Device B

Beta | Dev
-|-
![Screenshot 2023-06-23 at 3 36 16 PM](https://github.com/brave/brave-ios/assets/17885425/1a1d0f4c-0d43-4fd0-b898-4b9254ab7823) | ![Screenshot 2023-06-23 at 3 38 55 PM](https://github.com/brave/brave-ios/assets/17885425/76571cf9-d762-4a6b-8e8e-e76d2727439f)

**Scenario 3:** hash value for confirmation events when unblinded tokens spent

- Verified `rotating_hash` value is the same for each confirmation event (view, click, landed, dismissed)

Example | Example | Example
-|-|-
![Screenshot 2023-06-23 at 2 11 07 PM](https://github.com/brave/brave-ios/assets/17885425/50789b4e-d69a-4850-a784-8c1788e07575) | ![Screenshot 2023-06-23 at 2 11 57 PM](https://github.com/brave/brave-ios/assets/17885425/15ac1b64-f0df-42ec-a8e0-08346613398b) | ![Screenshot 2023-06-23 at 2 15 53 PM](https://github.com/brave/brave-ios/assets/17885425/83d664cd-1239-4d34-a70f-e48665812e5b)
