### ISSUE TITLE
Wallet: V2 Create a Wallet

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7619]
```[tasklist]
### Tasks
- [x] Wallet: V2 Welcome
- [x] Wallet: V2 Create a new Password
- [x] Wallet: V2 Back up Recovery Phrase
- [x] Wallet: V2 Verify Recovery Phrase
- [x] Wallet: V2 Biometrics
- [x] Wallet: V2 Confirmation
- [x] Wallet: V2 Restore Wallet
```

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 15.7.8 running 1.57 (23.8.29.22)
- Verified steps from [#7746](https://github.com/brave/brave-ios/pull/7746)
- Verified onboarding shows the new Wallet V2 UI
- Verified onboarding shows the new recovery phrase screen to type in 3 random words to verify backup
- Verified able to onboard by enabling biometric unlock
- Verified able to finish onboarding by skipping biometric unlock
- Verified able to restore a wallet using new onboarding screen
- Verified able to enable/skip biometric unlock when restoring a wallet
- Verified able to skip backup during onboarding when creating a new wallet 
----------
Verification passed on iPhone 13  with iOS 16.6 running 1.57 (23.8.29.22)
- Verified steps from [#7746](https://github.com/brave/brave-ios/pull/7746)
- Verified onboarding shows the new Wallet V2 UI
- Verified onboarding shows the new recovery phrase screen to type in 3 random words to verify backup
- Verified able to onboard by enabling biometric unlock
- Verified able to finish onboarding by skipping biometric unlock
- Verified able to restore a wallet using new onboarding screen
- Verified able to enable/skip biometric unlock when restoring a wallet
- Verified able to skip backup during onboarding when creating a new wallet 
----------
Verification passed on iPad Pro with iOS 16.6 running 1.57 (23.8.29.22)
- Verified steps from [#7746](https://github.com/brave/brave-ios/pull/7746)
- Verified onboarding shows the new Wallet V2 UI
- Verified onboarding shows the new recovery phrase screen to type in 3 random words to verify backup
- Verified able to onboard by enabling biometric unlock
- Verified able to finish onboarding by skipping biometric unlock
- Verified able to restore a wallet using new onboarding screen
- Verified able to enable/skip biometric unlock when restoring a wallet
- Verified able to skip backup during onboarding when creating a new wallet
