### ISSUE TITLE
Wallet: Filecoin basic support

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7809]
```[tasklist]
### Tasks
- [x] Filecoin account creation and displaying
- [x] Edit Filecoin account
- [x] Filecoin testnet network
- [x] Filecoin mainnet network
- [x] Filecoin network in send
- [x] Filecoin send transaction confirmation screen
- [x] Filecoin transaction summary
- [x] Filecoin transaction details screen
```

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.20.9)
- Verified Filecoin accounts are shown when a wallet is imported which has Filecoin balance
- Verified able to filter portfolio based on Filecoin accounts
- Verified able to select Filecoin for Buy screen
- Verified upgrading to 1.58 shows Filecoin token 
- Verified if a Filecoin account is not cretaed  selecting Filecoin from network prompts to create an account
- Verified on a clean install Filecoin account is not created by default
- Verified Filecoin Token is shown in protfolio on a clean install 
- Verified add account shows Filecoin as an option
- Verified able to submit a Send transaction from one FIL account to another
- Verified selecting to view transaction opens the correct block explorer
- Verified testnet accounts are listed when enabled
- Encountered [#8103](https://github.com/brave/brave-ios/issues/8103) & [#8104](https://github.com/brave/brave-ios/issues/8104)

<video src=https://github.com/brave/brave-ios/assets/17010094/35a6f284-18f7-40c0-bc05-6451c647271b> | <video src=https://github.com/brave/brave-ios/assets/17010094/2e8ab83d-4c36-43ef-ae7f-c4a1eda24b5e>
-- | --

![image](https://github.com/brave/brave-ios/assets/17010094/dc7944e2-0b96-437c-804f-18761df7e65e) | ![image](https://github.com/brave/brave-ios/assets/17010094/e6d854a3-6ad1-4427-a902-8f798482236d) | ![image](https://github.com/brave/brave-ios/assets/17010094/3f8aa262-df7f-420a-b345-0bc6c12c7e6e) | ![image](https://github.com/brave/brave-ios/assets/17010094/5e9e700e-01df-4e64-bb06-df28daaf9db1)
-- | -- | -- | --
