### ISSUE TITLE
Wallet: NFT Spam Management

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8006]
```[tasklist]
### Tasks
- [x] Add a dropdown that can display NFTs in Collection/Hidden/Spam category
- [x] User can long press NFT to hide NFT makes the NFT be displayed under Hidden
- [x] User can long press NFT to mark NFT as a spam NFT makes the NFT be displayed under Spam
- [x] User can long press  NFT under Spam to unhide or unspam the NFT
```
Setting `isSpam` should reflect to `visible` meaning if set `isSpam` to true, `visible` should be set to false, vice versa.

**Comment by nuo-xu** [comment]
Mark as QA/NO since some requirements are changed or updated in #8205 and full functionality can be verified in #8205
