### ISSUE TITLE
Wallet: NFT Tab V2

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8063]
```[tasklist]
### Tasks
- [x] Ghost loading while NFTs tab is loading metadata
- [x] New layout for auto-discovery pop-up
- [x] Group dropdown now has a counter with leading alignment
- [x] Remove NFT alert pop-up
```

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.30.17)
- Verified steps from [#8382](https://github.com/brave/brave-ios/pull/8382)
- Verified Auto-discovery popup is shown when a wallet is restored or created newly
- Verified loading state is shown on default NFT image when NFTs are being discovered and image is being loaded
- Verified long press on NFT shows `Don't not Show in Wallet` 
- Verified selecting it shows `Remove from Brave Wallet` popup
- Verified selecting `Remove` removes the NFT from Wallet display and not from the account 
- Verified NFT count is shown on both `Collected` and `Hidden` 
- Verified Network icon can be shown by enabling `Network Logo` in settings which is off by default

iPhone 13 (iOS 17.2) | iPad (iOS 16.7.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/cca197c3-4b40-4304-ab0a-efa46eee105f> | <video src=https://github.com/brave/brave-ios/assets/17010094/6f803201-50bb-4772-a1b6-6cf4417ce8ed> | <video src=https://github.com/brave/brave-ios/assets/17010094/fb547f4c-4496-4036-bf8b-3d4374e98ea4>

~Note: iOS 15 verification blocked on #8513~
