### ISSUE TITLE
Wallet: NFT Details V2

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8064]
```[tasklist]
### Tasks
- [x] New layout + network and account icons
- [x] Send/Hide/Mark as not junk/Remove
- [x] Remove confirmation pop-up
- [x] Updates on Navigation Bar
```

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.30.17)
- Verified steps from [#8408](https://github.com/brave/brave-ios/pull/8408)
- Verified NFT shows account blockie and network icon 
- Verified when NFT image is not loaded it shows a generic image
- Verified opening an NFT shows the NFT details 
- Verified 3 dot menu on each NFT 
- Verified 3 dot menu on collected NFT shows `Send`, `Hide`, `Don't Show in Wallet`
- Verified selecting `Send` pre-populates and loads the `Send` screen
- Verified selecting `Hide` moves the NFT into `Hidden` section
- Verified immediately selecting `Hide` and opening 3 dot menu shows `Unhide`
- Verified selecting `Don't Show in Wallet` shows the remove from wallet message, selecting `Remove` removes it from wallet
- Verified 3 dot menu on `Hidden` NFT shows `Mark as Not Junk` and `Don't Show in Wallet`
- Verified selecting `Mark as Not Junk` removes the `Junk` label and moves the NFT into `Collected` list
- Verified selecting `Don't Show in Wallet` shows the remove from wallet message, selecting `Remove` removes it from wallet


iPhone 13 (iOS 17.2) | iPad (iOS 16.7.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/abb58f25-d740-4e6f-9f09-b9b7405fe949> | <video src=https://github.com/brave/brave-ios/assets/17010094/57719e29-ea1a-4d97-8e72-bb01130631a8> | <video src=https://github.com/brave/brave-ios/assets/17010094/5c111cda-1c0f-424f-82a3-ad529131b10c>


~Note: iOS 15 verification blocked on #8513~
